#
# Don't change this file. Copy this file as Makefile.mine and then set the 
# variables. The Makefile.mine will be included by the root Makefile, but 
# ignored by .gitignore.
#

#
# Example programs. Set APP_NAME according to these values:
#
#   blink : rm
#   systick-blink : rm + ss
#
APP_NAME ?= blink
